import matplotlib.pyplot as plt
fig,ax=plt.subplots()
absx=np.mean(cens_numbers,axis=1)
ax.plot(absx,np.mean(rmse_mat,axis=1),'k-',label='Tobit Regression',color="green")
#ax.plot(absx,np.mean(rmse_mat,axis=1)+2*np.std(rmse_mat,axis=1),'k--',color="green")
#ax.plot(absx,np.mean(rmse_mat,axis=1)-2*np.std(rmse_mat,axis=1),'k--',color="green")
ax.plot(absx,np.mean(rmse_mat2,axis=1),'k-',label='Normal Regression')
#ax.plot(absx,np.mean(rmse_mat2,axis=1)+2*np.std(rmse_mat2,axis=1),'k--')
#ax.plot(absx,np.mean(rmse_mat2,axis=1)-2*np.std(rmse_mat2,axis=1),'k--')
legend = ax.legend(loc='upper center', shadow=True, fontsize='x-large')
plt.title('Mean RMSE (30loops) for different censoring proportions. 50x15 matrix-500zeros-test(0.2)')
plt.xlabel('Censoring Proportion in the training set')
plt.ylabel('TEST RMSE')
plt.show()
